### ISSUE TITLE
Yarn Ball misses an instance of npm i on npmjs.org

### ISSUE THREAD

**Issue by TylerBarnes** [JosephDuffy/Yarn-Ball#26]
![screen shot 2018-10-10 at 4 49 28 pm](https://user-images.githubusercontent.com/14190743/46772355-78ec6680-ccac-11e8-9481-99802085f939.png)

The most important `npm i` is missed! The one that you can click to copy.

**Comment by JosephDuffy** [comment]
Yarn Ball is not an dependency so it's not published on NPM; "installing" Yarn Ball wouldn't provide anything of any use.

I've opened a PR to mark add `"private": true` to the package.json, which hopefully makes this clearer

**Comment by TylerBarnes** [comment]
You're misunderstanding this issue. Yarn ball is supposed to replace "npm i" with "yarn add" around the web. When you go to npmjs.com it doesn't do this which is actually the most useful place for yarnball. This isn't about yarnball not being on npmjs.com.
